version: 2
updates:
  - package-ecosystem: "gradle"
    directories:
      - "gradle-platform"
      - "gradle-build-logic"
      - "gradle-build-logic/gcx-plugins"
      - "libs/*"
    target-branch: "main"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Europe/Berlin"
  - package-ecosystem: "github-actions"
    target-branch: "main"
    directories:
      - ".github/actions/*"
      - "/"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Europe/Berlin"
