version: 2
updates:
  - package-ecosystem: "gradle"
    open-pull-requests-limit: 20
    directories:
      - "gradle-platform"
    target-branch: "main"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Europe/Berlin"
    registries:
      - gradle-plugins
  - package-ecosystem: "github-actions"
    target-branch: "main"
    directories:
      - ".github/actions/*"
      - "/"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Europe/Berlin"

registries:
  gradle-plugins:
    type: maven-repository
    url: https://plugins.gradle.org/m2/
