version: 2
updates:
  - package-ecosystem: "gradle"
    open-pull-requests-limit: 20
    directories:
      - "gradle-platform"
    target-branch: "main"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Europe/Berlin"
  - package-ecosystem: "github-actions"
    target-branch: "main"
    directories:
      - ".github/actions/*"
      - "/"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Europe/Berlin"
