name: CI
on:
  workflow_dispatch:
  push:
    branches: [ ]

jobs:
  lint_tests:
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    name: Code-Linting, Unit-/Integration-Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'liberica'
      - name: Gradle Setup
        uses: gradle/actions/setup-gradle@v4
      - name: Run gradlew check
        run: ./gradlew check --info
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "*/*/build/test-results/test/*.xml"

  publish_snapshot:
    permissions:
      contents: read
      packages: write
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    name: Publishing Snapshot
    needs: lint_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          semver_only: true
      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: preminor
      - run: |
          SUFFIX="SNAPSHOT"
          if [ "${BRANCH_NAME}" != "main" ]; then
            SUFFIX="${SUFFIX}-${BRANCH_NAME}"
          fi
          echo "SNAPSHOT_VERSION=${{ steps.bump-semver.outputs.new_version }}-${SUFFIX}" >> "$GITHUB_OUTPUT"
        id: snapshot_version
      - run: ./gradlew release -Pversion=${{ steps.snapshot_version.outputs.SNAPSHOT_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
