name: CI
on:
  workflow_dispatch:
  push:
    branches: [ ]

jobs:
  lint_tests:
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    name: Code-Linting, Unit-/Integration-Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'liberica'
      - name: Gradle Command - check
        uses: gradle/actions/setup-gradle@v4
      - name: Run gradlew check
        run: ./gradlew check --info
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "*/*/build/test-results/test/*.xml"
