name: CI
on:
  workflow_dispatch:
  workflow_call:

jobs:
  lint_tests:
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    name: Code-Linting, Unit-/Integration-Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-jdk-gradle

      - name: Run gradlew check
        run: ./gradlew check --info

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "*/*/build/test-results/test/*.xml"
