name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"

concurrency:
  group: release_group
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml

  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.calver.outputs.CALVER }}
    permissions:
      contents: write
      packages: write
    needs: [ ci ]

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-jdk-gradle

      - run: |
          # Generate CalVer in the form YearMonthDayHour
          echo "CALVER=$(date +'%Y%m%d%H')" >> "$GITHUB_OUTPUT"
        id: calver

      - uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.calver.outputs.CALVER }}
          makeLatest: true
          generateReleaseNotes: true
          commit: ${{ github.sha }}
          tag: ${{ steps.calver.outputs.CALVER }}
          allowUpdates: true

      - uses: ./.github/actions/publish
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ steps.calver.outputs.CALVER }}

  publish_sboms:
    needs:
      - release
    uses: ./.github/workflows/upload-sboms.yaml
    name: Publish SBOMs for Release of all components
    with:
      version: ${{ needs.release.outputs.version }}
    secrets:
      DEPENDENCYTRACK_API_BASIC_AUTH_PW: ${{ secrets.DEPENDENCYTRACK_API_BASIC_AUTH_PW }}
      DEPENDENCYTRACK_APIKEY: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
