name: Release

on:
  push:
    tags:
      - "^v[0-9]+\.[0-9]+\.[0-9]+-?.*$"

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: [ ci ]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-jdk-gradle

      - name: Publish package
        run: ./gradlew publish -Pversion=${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
