name: Release

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: "possible values: major, minor, patch (default)"
        required: true
        default: patch

jobs:

  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ inputs.version_bump }}
    outputs:
      new_version: ${{ steps.tag_version.outputs.new_version }}

  release:
    runs-on: ubuntu-latest
    needs: [bump-version]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '17'

      - name: Publish
        uses: gradle/gradle-build-action@v2.4.0
        with:
          arguments: publish -Pversion=${{ needs.bump-version.outputs.new_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
