name: Upload SBOMs

on:
  workflow_run:
    workflows:
      - Publish Snapshots
      - Release
    types:
      - completed

jobs:
  upload-lib-sboms:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        componentName:
          - artur-bosch-detekt
          - base-entity
          - kotlin-logger
          - test-containers
          - tls-helper

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: sbom

      - uses: ./.github/actions/upload-sbom
        with:
          bom-path: "libs/${{ matrix.componentName }}/build/reports/bom.json"
          dependencytrack-api-key: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
          dependencytrack-api-basic-auth-pw: ${{ secrets.DEPENDENCYTRACK_API_BASIC_AUTH_PW }}
          project-name: "gcx-common-libs/${{ matrix.componentName }}"

  upload-plugins-sbom:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: sbom

      - uses: ./.github/actions/upload-sbom
        with:
          bom-path: "gradle-build-logic/gcx-plugins/build/reports/bom.json"
          dependencytrack-api-key: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
          dependencytrack-api-basic-auth-pw: ${{ secrets.DEPENDENCYTRACK_API_BASIC_AUTH_PW }}
          project-name: "gcx-common-libs/gcx-plugins"
